name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Code Style Analysis
        run: composer run lint

      #      - name: Static Code Analysis
      #        run: composer run static-code-analysis

      - name: Run Testsuite
        run: composer run test

#      - name: Require Vapor CLI
#        run: composer global require laravel/vapor-cli

#      - name: Deploy to AWS via Vapor
#        run: |
#          vapor deploy production
#        env:
#          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
